# Generated by Django 4.2.4 on 2024-07-06 08:10

import atashbaan.images.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "image",
                    models.ImageField(upload_to=atashbaan.images.models.user_uploads_path, verbose_name="تصویر"),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[("processed", "پردازش شده"), ("unprocessed", "پردازش نشده")],
                        default="unprocessed",
                        max_length=20,
                        verbose_name="برچسب",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد")),
                ("last_modified", models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی")),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
