# Generated by Django 4.2.4 on 2023-10-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0002_alter_image_options_image_created_at_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="image",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tag", "processed")), fields=("image",), name="unique_processed_image"
            ),
        ),
    ]
