# Generated by Django 4.2.4 on 2023-10-07 16:20

import atashbaan.images.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0003_image_unique_processed_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                unique=True, upload_to=atashbaan.images.models.user_uploads_path, verbose_name="تصویر"
            ),
        ),
    ]
